// =====================================================
//
// This file was generated by LinearMPC.jl
// If you find it useful, consider citing the paper:
//
//     "A Dual Active-Set Solver for Embedded Quadratic Programming Using Recursive LDL Updates" 
//     Arnström, D. and Bemporad, A. and Axehill, D.
//     IEEE Transactions on Automatic Control
//
// Also, any feedback or success stories from using LinearMPC.jl and/or DAQP
// is gladly recieved at daniel.arnstrom@gmail.com
//
// =====================================================
#ifndef MPC_FUNCS_H
#define MPC_FUNCS_H

#include "types.h"
#include "constants.h"
// Settings prototype
extern DAQPSettings settings;

#undef NX
#define NX 4
#undef N_CONSTR
#define N_CONSTR 10
#undef N_SIMPLE
#define N_SIMPLE 0 
// Workspace prototypes
extern c_float M[40];
extern c_float dupper[10];
extern c_float dlower[10];
extern c_float Rinv[10];
extern int sense[10];

extern c_float x[5];
extern c_float xold[5];

extern c_float lam[15];
extern c_float lam_star[15];
extern c_float u[5];

extern c_float L[120];
extern c_float D[15];
extern c_float xldl[15];
extern c_float zldl[15];

extern int WS[15];

extern DAQPWorkspace daqp_work;

#endif // ifndef MPC_FUNCS_H
#ifndef MPC_FUNCS_MPC_H
#define MPC_FUNCS_MPC_H

#define N_THETA 11
#define N_STATE 6
#define N_REFERENCE 2
#define N_DISTURBANCE 1
#define N_CONTROL_PREV 2
#define N_LINEAR_COST 0
#define N_CONTROL 2

extern c_float mpc_parameter[11];
extern c_float Dth[110];
extern c_float du[10];
extern c_float dl[10];

extern c_float Uth_offset[22];

extern c_float u_offset[2];

extern c_float uscaling[2];

void mpc_update_qp(c_float* th, c_float* dupper, c_float* dlower);
void mpc_get_solution(c_float* th, c_float* control, c_float* xstar);
#if N_LINEAR_COST > 0
int mpc_compute_control(c_float* control, c_float* state, c_float* reference, c_float* disturbance, c_float* linear_cost);
#else
int mpc_compute_control(c_float* control, c_float* state, c_float* reference, c_float* disturbance);
#endif
#define N_MEASUREMENT 2
extern c_float MPC_PLANT_DYNAMICS[60];
extern c_float MPC_MEASUREMENT_FUNCTION[16];
extern c_float K_TRANSPOSE_OBSERVER[12];
void mpc_predict_state(c_float* state, c_float* control, c_float* disturbance);
void mpc_correct_state(c_float* state, c_float* measurement, c_float* distrubance);
#endif // ifndef MPC_FUNCS_MPC_H
