name: Run benchmarks
on:
  pull_request:
    # Only trigger the benchmark job when you add `run benchmark` label to the PR
    types: [labeled, opened, synchronize, reopened]
concurrency:
  # Skip intermediate builds: always.
  # Cancel intermediate builds: only if it is a pull request build.
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}
jobs:
  Benchmark:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      actions: write # needed to allow julia-actions/cache to proactively delete old caches that it has created
      contents: read
    if: contains(github.event.pull_request.labels.*.name, 'benchmark')
    steps:
      - uses: actions/checkout@v4
      - uses: julia-actions/setup-julia@latest
      - name: Cache artifacts
        uses: actions/cache@v4
        env:
          cache-name: cache-artifacts
        with:
          path: ~/.julia/artifacts 
          key: ${{ runner.os }}-test-${{ env.cache-name }}-${{ hashFiles('**/Project.toml') }}
          restore-keys: |
            ${{ runner.os }}-test-${{ env.cache-name }}-
            ${{ runner.os }}-test-
            ${{ runner.os }}-
      - name: Install dependencies
        run: julia -e 'using Pkg; pkg"add JSON PkgBenchmark BenchmarkCI@0.1"'
      - name: Run benchmarks
        run: julia benchmark/run_benchmarks.jl
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}