name: Benchmark
on:
  pull_request_target:
    branches: [ main ]
    types: [labeled, opened, synchronize, reopened]
concurrency:
  group: benchmark-${{ github.ref }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}
permissions:
  pull-requests: write    # needed to post comments
jobs:
  bench:
    runs-on: ubuntu-latest
    if: ${{ contains(github.event.pull_request.labels.*.name, 'benchmark') }}
    steps:
      - uses: MilesCranmer/AirspeedVelocity.jl@action-v1
        with:
          julia-version: '1'